<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.lista_geral' => 'b88bed6d4cdfc0df70ffa9afec01dd9415d25cd6',
  'content_type.panopoly_page' => '82d0ba80c312494f307e916368860f49ed23f9e5',
  'field.node.body.lista_geral' => '15e0782de745e41f7533457428e8488329640d38',
  'field.node.body.panopoly_page' => 'e9e103c15cfc80b7d3f4e312133e4e3e0e39e033',
  'field.node.field_featured_categories.panopoly_page' => '2146fc682cd09044f1285d1496e55125a453340e',
  'field.node.field_featured_image.panopoly_page' => '860d20372abd5a78e21b74b881a8e1baedb278ae',
  'field.node.field_featured_status.panopoly_page' => '550cece7031bc26168ba8f7ac4b7a0c2ffc38e49',
  'image_style.panopoly_image_half' => '7138c61a5899d28aa13bdbc3545785acc264ee6e',
  'image_style.panopoly_image_quarter' => '84e25cfcc6b4afda1d87cc39d5e9842d85319305',
  'permission.create_lista_geral_content' => '706b77b1a1f3e655d521744be162dc7a556550f5',
  'permission.create_panopoly_page_content' => 'f8a80fbcabafd750a33852cfc626b90e56f6310b',
  'permission.delete_any_lista_geral_content' => '34e0e18e0c9cf84269340b7037ef83bd3c82e9e3',
  'permission.delete_any_panopoly_page_content' => 'e62ee4e58de136a79ff61f5ba7d66a4c51ad79af',
  'permission.delete_own_lista_geral_content' => '59c6b103fbd6eb5db4bc9b6f64beab1001ce837c',
  'permission.delete_own_panopoly_page_content' => 'f88ebb3749078e3839dd91d3ea4aa84041f2e4b9',
  'permission.edit_any_lista_geral_content' => '5e3620a4b5da52e68487538ac5a18bef83df87e6',
  'permission.edit_any_panopoly_page_content' => '4e8e639dc497aa95d61f4edadebc045275dd0ddc',
  'permission.edit_own_lista_geral_content' => '8cccb714e91718f256a0ecf9be10ea734df6ce14',
  'permission.edit_own_panopoly_page_content' => '496174d5c05f7852192ed392b4c04c091ec30940',
  'vocabulary.music_style' => '9c78f097b38a9205f28f989d1fcca5804a8028a3',
  'vocabulary.panopoly_categories' => '9bb404bd9ec3a5d364ec18cb7f165f013568a89f',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'node',
  'field_sql_storage',
  'text',
  'taxonomy',
  'options',
  'image',
  'list',
  'manualcrop',
);
